# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='agrees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='disagrees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='opinion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
